//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafio_API_vs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reunion
    {
        public int id_reunion { get; set; }
        public string titulo { get; set; }
        public string descripción { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
